### ISSUE TITLE
Although patch file is created I am getting an  error mv: missing destination file operand after '0001-Create-Patch-File.patch' can anyone help in resolving this issue

### ISSUE THREAD

**Issue by Narayamini** [insidesherpa/bank-mergeCoTechTask1#115]
![Screenshot (218)](https://user-images.githubusercontent.com/51707969/81346620-384b0e00-90d8-11ea-8a96-50a0a03be486.png)

**Comment by IFHAM99** [comment]
there is a space that you've missed, copy this-
mv 0001-Create-Patch-File.patch ../.

**Comment by shubhsiro** [comment]
yeah this worked
thanks

**Comment by Narayamini** [comment]
Yeah ,thank you
