### ISSUE TITLE
NameError : name prices not defined

### ISSUE THREAD

**Issue by chaitanya642000** [insidesherpa/bank-mergeCoTechTask1#122]
I  am  getting error at 'prices[stock] = price' line .
Here is the screenshot of error
![error](https://user-images.githubusercontent.com/48641297/81430017-58340d80-917c-11ea-8160-b54c179de921.png)

**Comment by sRajdeep617** [comment]
just before line 34 i.e. for quote in quotes:
write
prices = {}

**Comment by ankitkashyap12** [comment]
i have done that but I get keyerroe for 'DEF' when passed in getratio function.Seems like data point doesn't return any stock named DEF.what should I do?

**Comment by ankitkashyap12** [comment]
![client py](https://user-images.githubusercontent.com/22171624/81493878-d0f0b200-92c1-11ea-8eb9-6d96986f3e99.PNG)
though after checking I found that datapoint return ABC and DEF info..still this is giving errors

**Comment by sRajdeep617** [comment]
there is a problem in line 27
the identation of this line do not goes with line 23, it goes with line 18
press backspace in line 27 and make it in accordance with line 18
![WhatsApp Image 2020-05-11 at 11 46 40 AM](https://user-images.githubusercontent.com/50442114/81529745-263dc980-937d-11ea-895e-5de78aa3b656.jpeg)

**Comment by ankitkashyap12** [comment]
Thanks for the help.

**Comment by chaitanya642000** [comment]
thanks @sRajdeep617  for your response but I am still getting an error 
Here is the screen shot
![error](https://user-images.githubusercontent.com/48641297/82140771-bf258680-984e-11ea-88ed-d60c7d6264b7.png)

**Comment by chaitanya642000** [comment]
Thanks @sRajdeep617  for your help
