### ISSUE TITLE
unindent !!

### ISSUE THREAD

**Issue by TD-17** [insidesherpa/bank-mergeCoTechTask1#125]
![Screenshot (34)](https://user-images.githubusercontent.com/61655940/81486020-7dee0f00-926f-11ea-915e-b0e48c3f1c05.png)
how it is unindented??

**Comment by saquib77** [comment]
same problem ! 
unindent ! 
How ?

**Comment by TD-17** [comment]
> 
> 
> same problem !
> unindent !
> How ?

oh its clear now!! Just watch the video provided there.

**Comment by Neha-Jacob** [comment]
i hv the same problem....which video??

**Comment by TD-17** [comment]
> 
> 
> i hv the same problem....which video??

![Screenshot (37)](https://user-images.githubusercontent.com/61655940/81668738-b7d33700-9462-11ea-8e69-61a554a5512a.png)
this one from the given instructions page
