### ISSUE TITLE
showing keyerror. how to solve it?

### ISSUE THREAD

**Issue by Neha-Jacob** [insidesherpa/bank-mergeCoTechTask1#134]
![Screenshot from 2020-05-12 15-17-24](https://user-images.githubusercontent.com/60283339/81669892-7b083f80-9464-11ea-9f4e-19eeb269978e.png)

**Comment by Mrinalkothari** [comment]
Same with me i also want to know

**Comment by harnoor497** [comment]
same issue with me . what to do?

**Comment by Neha-Jacob** [comment]
Got it. I missed out the line below:
prices[stock]=price
