### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by prachirathod99** [insidesherpa/bank-mergeCoTechTask1#138]
C:\Users\.....\JPMC-tech-task-1>python server.py
Traceback (most recent call last):
  File "server.py", line 21, in <module>
    from itertools import izip
ImportError: cannot import name 'izip' from 'itertools' (unknown location)

**Comment by ankmish** [comment]
If you are using python3.x version, **izip** is not supported. New version of python provide default zip() function.

Just comment the `from itertools import izip` and change function name **izip()** to **zip()**, it will work.

Hope this will resolve your problem.

**Comment by prachirathod99** [comment]
Hi,

Thank you so much I tried this and it did work!!

Thank you,

Prachi Rathod

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
