### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by JKeerthi-21** [insidesherpa/bank-mergeCoTechTask1#147]
![KeyError](https://user-images.githubusercontent.com/63769816/81974850-c167c500-9643-11ea-95e4-2cbd96c69f75.png)

**Comment by JKeerthi-21** [comment]
Can someone please help me with this...

**Comment by AJTopisano** [comment]
Even i'm getting KeyError, Dont know why

**Comment by AJTopisano** [comment]
@JKeerthi-21  you havent put anything in your dictionary..its empty..
it should look like this
if __name__ == "__main__":
  for _ in iter(range(N)):
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
    prices = {}  
    for quote in quotes:
      stock, bid_price, ask_price, price = getDataPoint(quote)
      prices[stock] = price
      print ("Quoted %s at (bid:%s, ask:%s, price:%s)" % (stock, bid_price, ask_price, price))
    
    print("Ratio %s" % getRatio(prices["ABC"], prices["DEF"]) )

**Comment by JKeerthi-21** [comment]
Okay, thank you...
