### ISSUE TITLE
Error HTTP Server not found while running python client.py command

### ISSUE THREAD

**Issue by thathgarsahil** [insidesherpa/bank-mergeCoTechTask1#163]
![Screenshot (1215)](https://user-images.githubusercontent.com/54679372/82291085-f0749280-99c5-11ea-9dd9-f0aeaf767961.png)

![Screenshot (1213)](https://user-images.githubusercontent.com/54679372/82291419-8dcfc680-99c6-11ea-9079-58a2bbdd1085.png)

After running server.py in admin cmd prompt & the client.py in another cmd prompt window. I am getting this error. Any idea how to fix this??

**Comment by kamleshdhondge** [comment]
There might an issue while running the server.py. First the Server program needs to be runned and then client.  It might be that the server libs are not installed on your machine. Can you please add  a screenshot of server console?

**Comment by thathgarsahil** [comment]
It is running well on server side, without any error. I can attach the screenshot. I changed the port to 8085. Now its working. But not on default 8080.

**Comment by kamleshdhondge** [comment]
Well if changing ports its working means, there is another process which has taken your port 8080, (generally Local server). on your machine. If you change the port to 8085, make sure to change the line 27 on client_py file to "QUERY = `"http://localhost:8085/query?id={}""` else it wont work
`

**Comment by thathgarsahil** [comment]
Yes i did it. It is solved now.
