### ISSUE TITLE
query in server3 command

### ISSUE THREAD

**Issue by Jeet-Prajapati** [insidesherpa/bank-mergeCoTechTask1#185]
C:\Users\jeetp\JPMC-tech-task-1-py3>python server3.py
HTTP server started on port 8080

i ran this command and it has just stopped there,and not prompting new line.
is the server has started successfully or there is some problem?

**Comment by Kritika37** [comment]
Hey, that's how the server is started, there is no error

**Comment by Jeet-Prajapati** [comment]
thank you.
