### ISSUE TITLE
After downloading my zip file i find the patch file is not present

### ISSUE THREAD

**Issue by SAHU-01** [insidesherpa/bank-mergeCoTechTask1#242]
After downloading my zip file i find the patch file is not present,

if i click it on the repl website it appears but on downloading it isn't showing

what should I do next?

check the image below u can see my patch file on the repl website but on downloading the zip file i don't find my patch file
![image](https://user-images.githubusercontent.com/71656941/100466025-430dd480-30f6-11eb-84a5-db91d6d0fa46.png)

**Comment by cdacones** [comment]
@SAHU-01 I had the same problem as well. Move the patch file with the REPL into the jpm_module_1 folder then download the zip.  After unzip the file, and the .patch file should be in the jpm folder.

**Comment by bubbles187** [comment]
@SAHU-01 I had the same problem as well. Move the patch file within the REPL into the jpm_module_1 folder then download.

**Comment by HMHarris-git** [comment]
Patch file is not present in zip file..
Code edited on REPL.it
Local Machine :: Windows 10
Browser :: Google Chrome

![image](https://user-images.githubusercontent.com/76788594/103442789-4d843680-4c7f-11eb-8867-a695c73ed4f6.png)
![image](https://user-images.githubusercontent.com/76788594/103442821-6bea3200-4c7f-11eb-8ba5-afb2e3107197.png)

**Comment by Nirajan999** [comment]
Yeah, I am having the same problem as well, I tried moving it in the jpm_module_1 but it still didn't do anything for me
