### ISSUE TITLE
Patch file not showing up in zip file

### ISSUE THREAD

**Issue by vpillai002** [insidesherpa/bank-mergeCoTechTask1#247]
When I download the files as a zip file, and I unzip the file, I can't seem to find the .patch file I need to submit for task 1.

**Comment by ashaharney** [comment]
Have you tried moving the patch file under jpm_module_1 folder and then downloading? I had the same issue but this fixed it

**Comment by vpillai002** [comment]
Thank you! This worked and fixed my issue!

**Comment by Nirajan999** [comment]
Hey, I tried moving it under jpm_module_1 and it still didn't show up for me? Any other suggestions on what to do?
