### ISSUE TITLE
Error message in main "KeyError: 'ABC'"

### ISSUE THREAD

**Issue by sahanabela** [insidesherpa/bank-mergeCoTechTask1#25]
I am using the Repl.it platform for task one and am on chrome (Windows OS). When I try to run the program by clicking the 'start' button, I see the following error on the console. I am not sure why this is giving me an error as I followed the instructions on the docs. Thank you!

![Capture](https://user-images.githubusercontent.com/55221478/69657664-59470780-1040-11ea-9a84-57da63bb6a6e.JPG)

**Comment by jbf-insidesherpa** [comment]
@sahanabela your error is similar to this resolved issu: https://github.com/insidesherpa/JPMC-tech-task-1/issues/24

 Make sure your indentation is correct as that will dictate whether or not prices['ABC'] and prices['DEF'] are defined
