### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by neissacodes** [insidesherpa/bank-mergeCoTechTask1#26]
prices = {} causes an indentation error although I followed all the instructions properly.

**Comment by jbf-insidesherpa** [comment]
@neissacodes did you follow the workaround suggested in the [guide](https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/repl_mod1_v4.pdf)? It's in the basic repl editing section (slides 13-14)
