### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by sushilca98** [insidesherpa/bank-mergeCoTechTask1#27]
import urllib2
import time
import json
import random

# Server API URLs
QUERY = "http://localhost:8080/query?id={}"

# 500 server request
N = 500

def getDataPoint(quote):
	""" Produce all of the needed values to generate a datapoint """
	""" ------------- Update this function ------------- """
	stock = quote['stock']
	bid_price = float(quote['top_bid']['price'])
	ask_price = float(quote['top_ask']['price'])
	price = (bid_price + ask_price)/2
	return stock, bid_price, ask_price, price

def getRatio(price_a, price_b):
  if (price_b == 0):
    return
  return price_a/price_b

# Main
if __name__ == "__main__":

	# Query the price once every N seconds.
	for _ in xrange(N):
		quotes = json.loads(urllib2.urlopen(QUERY.format(random.random())).read())
    prices = {}
    for quote in quotes:
            stock, bid_price, ask_price, price = getDataPoint(quote)
            prices[stock] = price
            print "Quoted %s at (bid:%s, ask:%s, price:%s)" % (stock, bid_price, ask_price, price0
    print "Ratio %s" % getRatio(prices['ABC'], prices['DEF'])
![Error](https://user-images.githubusercontent.com/53387282/69847604-72141080-122c-11ea-82ef-647ed492877d.PNG)

**Comment by jbf-insidesherpa** [comment]
@sushilca98 you have a similar issue that's already been discussed here: https://github.com/insidesherpa/JPMC-tech-task-1/issues/26#issuecomment-560016151

Please follow the suggested workarounds in the guide
