### ISSUE TITLE
jpm_module_1 command 

### ISSUE THREAD

**Issue by ghost** [insidesherpa/bank-mergeCoTechTask1#277]
<img width="1440" alt="Screen Shot 2021-11-20 at 1 01 37 PM" src="https://user-images.githubusercontent.com/94758613/142736691-a79bd952-0001-4f2b-85eb-45df9044b54e.png">

I'm using REPL on Mac in Google Chrome. I tried inputting the jpm_module_1 command but it wouldn't initialize the jpm_module_1 directory as a git repository. After os.system('bash') nothing would happen. This is what is supposed to come up. 
<img width="725" alt="Screen Shot 2021-11-20 at 1 11 10 PM" src="https://user-images.githubusercontent.com/94758613/142736859-bb207dc4-be49-4df8-b538-71869da78318.png">

 How do I fix this?

**Comment by Rishik311** [comment]
Have you been able to solve it?I am facing the same problem.
