### ISSUE TITLE
Phase 1 error

### ISSUE THREAD

**Issue by sahanabela** [insidesherpa/bank-mergeCoTechTask1#28]
I fixed the indentation in the main in client.py but it is still giving me the same error. I am pretty sure I fixed the indentation and I followed the instructions, so I am not sure what the issue is. Thank you!

![jpmorganphase1](https://user-images.githubusercontent.com/55221478/69908762-61db6d00-13b5-11ea-8223-add9daf3d43a.JPG)

**Comment by jbf-insidesherpa** [comment]
@sahanabela you didn't assign anything in `prices` in the second for loop that's why `prices['ABC']` and `prices['DEF']` won't ever be defined in your code. Please re-read the guide as you missed some code that must be there.
