### ISSUE TITLE
issue with 1st module for me: help!

### ISSUE THREAD

**Issue by marxyng** [insidesherpa/bank-mergeCoTechTask1#29]
![issue_with_jpmorgan](https://user-images.githubusercontent.com/38600509/71146093-727b4800-21e9-11ea-9038-79b26cfa69a2.jpg)

Hope you can help with this.  I tried uploading a picture.  It said this: https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/repl_mod1_v4.pdf

**Comment by Yedzinovich** [comment]
Check your spelling. It seems like your word patch in Create-patch-File should be lowercase, but you type capital. Let me know if it helps

**Comment by jbf-insidesherpa** [comment]
@marxyng @Yedzinovich is correct. Your spelling is wrong for the patch file you're trying to move. The environment is case sensitive so be careful with that.
