### ISSUE TITLE
JP Morgan Virtual Internship Task 1

### ISSUE THREAD

**Issue by Fortune-Adekogbe** [insidesherpa/bank-mergeCoTechTask1#33]
Good day, I have not been able to run my code on repl because a FileNotFoundError as shown in the attached image keeps interfering. I use windows 10 OS and I am done with the task, I just need to verify the unit testing. I have tried it on Microsoft edge browser and chrome. Please look into this for me.
![Screenshot (108)](https://user-images.githubusercontent.com/53936357/71559936-fc39d980-2a63-11ea-875e-ab65491e3678.png)

**Comment by readhapark** [comment]
Hey, you need to change( '/home/runner/jpm_module_1') to ( '/home/runner/JPM-MODULE1-PY3-REPL-3/jpm_module_1') this is the right working directory and ensure that you have changed directory to jpm_module_1

**Comment by Fortune-Adekogbe** [comment]
Thanks a lot

**Comment by rhtydv27** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/60359628/81182617-a6ee7580-8fcb-11ea-92bd-00efe5c18164.png)
error

**Comment by abbylester1** [comment]
> ![Screenshot (38)](https://user-images.githubusercontent.com/60359628/81182617-a6ee7580-8fcb-11ea-92bd-00efe5c18164.png)
> error

Any solution to this , I am stucked at the same stage.

**Comment by shubham1105pawar** [comment]
Re-write the code from scratch if this not help just setup the environment  with the help of attached documentation.
