### ISSUE TITLE
Can't find Patch file after moving it

### ISSUE THREAD

**Issue by gitOnMyLevel** [insidesherpa/bank-mergeCoTechTask1#36]
Good evening. I am currently on Task 1 of the internship, and I just finished all the coding. Everything works, I made the patch file but it does not appear on the left side menu. I followed all the steps, so I don't know what is causing the issue. Help would be most appreciated.

**Comment by gitOnMyLevel** [comment]
![2020-03-23 (1)](https://user-images.githubusercontent.com/9745575/77281051-69908b80-6c9c-11ea-8ec0-93b5c9fea25e.png)

![2020-03-23 (2)](https://user-images.githubusercontent.com/9745575/77281064-7319f380-6c9c-11ea-94fa-db6a05647b72.png)

**Comment by Annihilator99** [comment]
Facing the same issue. The patch file shows up on running the 'ls' command
![image](https://user-images.githubusercontent.com/31548260/77630443-0e4aeb80-6f71-11ea-9318-5ca9bc4f88e1.png)

But does not show up in the side menu 
![image](https://user-images.githubusercontent.com/31548260/77630591-523df080-6f71-11ea-9645-e2ad4482be0e.png)

Nor does it show up when I download the zip file
![image](https://user-images.githubusercontent.com/31548260/77631033-08093f00-6f72-11ea-90b9-687a1b7fa283.png)

Any help would be highly appreciated. Thank you.

**Comment by Thenvir** [comment]
Facing the same issue. Tried fiddling with the directories when moving the patch file but it doesn't want to show up on the left sidebar.

**Comment by neonotfrommatrix** [comment]
I am having the same issue as well.

EDIT:  I just downloaded the entire project rather than just the jpm_module to get the patch file.

**Comment by jbf-insidesherpa** [comment]
@gitOnMyLevel  and @Thenvir apologies for getting back to this only now just follow @neonotfrommatrix solution of downloading the entire project to get the patch file.

Another way to get around this seemingly intermittent issue is by checking running
`cat <patch_file_name` so that you can print out all the contents
Then you can just copy the patch file contents into your own text editor and save it as a .patch file.

**Comment by gitOnMyLevel** [comment]
No worries, it's a strange time right now.
