### ISSUE TITLE
unable to convert to patch file

### ISSUE THREAD

**Issue by abhijeetpatri** [insidesherpa/bank-mergeCoTechTask1#37]
showing **fatal: not a git repository (or any parent up to mount point /home/runner**

**Comment by jbf-insidesherpa** [comment]
@abhijeetpatri sorry to get to this only now. I presume you're using REPL here? The reason you're getting that error is because you're trying to do a git command in a directory that isn't a git repository. You should've first changed your directory to jpm_module_1 by doing **cd jpm_module_1**

**Comment by abhijeetpatri** [comment]
Still the problem is not solved...it is showing the same thing

**Comment by jbf-insidesherpa** [comment]
@abhijeetpatri can you provide screenshots of the state of your REPL?
