### ISSUE TITLE
Creating patch file Issue 

### ISSUE THREAD

**Issue by Lina-crypto** [insidesherpa/bank-mergeCoTechTask1#41]
After I create my patch file, I am unable to download as zip. When I click the button, nothing happens

**Comment by jbf-insidesherpa** [comment]
@Lina-crypto are you using REPL? If so, perhaps you can retry with a fresh REPL instance ? (better if you create your own REPL account and then you're able to save the state wherein you have the patch file already and just retry to download)

**Comment by Lina-crypto** [comment]
Yes, I am using REPL. I tried with a fresh REPL and I created an account as well and it has not worked. Do you have any other recommendations?

**Comment by jbf-insidesherpa** [comment]
What browser are you using @Lina-crypto also, if you can, can you share the link to your REPL? (i.e. invite+ button)

**Comment by Lina-crypto** [comment]
I actually ended up using another browser and it worked. I submitted my task. Thank you!
