### ISSUE TITLE
server3.py , client3.py errors

### ISSUE THREAD

**Issue by mgamiao** [insidesherpa/bank-mergeCoTechTask1#46]
I was in the middle of doing client_test.py then I got disconnected due to poor internet connection. After reloading the page, I did the initialization steps (the one that you set up your email/name etc.) and I don't know what's the next thing to do.

![image](https://user-images.githubusercontent.com/63153996/79440939-31fdd080-8009-11ea-81c6-1841d1c5cc3d.png)

**Comment by mgamiao** [comment]
I'm using repl in chrome

**Comment by avinash1605** [comment]
Hi,
I am facing the same issue.
Can you tell me how to resolve it

**Comment by mgamiao** [comment]
> Hi,
> I am facing the same issue.
> Can you tell me how to resolve it

I just redid everything
