### ISSUE TITLE
TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by mgamiao** [insidesherpa/bank-mergeCoTechTask1#47]
![image](https://user-images.githubusercontent.com/63153996/79448658-62973780-8014-11ea-810c-c34d841d98d1.png)

**Comment by mon2barot** [comment]
On line 57 it should be prices instead of price; your code is missing an 's'. Additionally, there's an opening bracket before getRatio and a closing bracket at the end. However, after doing this I run into a Key Error: 'ABC. Nevertheless, it solves the subscriptable error.

**Comment by mgamiao** [comment]
> On line 57 it should be prices instead of price; your code is missing an 's'. Additionally, there's an opening bracket before getRatio and a closing bracket at the end. However, after doing this I run into a Key Error: 'ABC. Nevertheless, it solves the subscriptable error.

Thank you
