### ISSUE TITLE
Client Server file issues

### ISSUE THREAD

**Issue by chetali19** [insidesherpa/bank-mergeCoTechTask1#49]
C:\Users\Desktop\JPMC-tech-task-1>python server.py
  File "server.py", line 217
    print 'HTTP server started on port 8080'
                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('HTTP server started on port 8080')?

C:\Users\Desktop\JPMC-tech-task-1>python client.py
  File "client.py", line 57
    print "Quoted %s at (bid:%s, ask:%s, price:%s)" % (stock, bid_price, ask_price, price)
                                                  ^
SyntaxError: invalid syntax

C:\Users\Desktop\JPMC-tech-task-1>python client.py
Traceback (most recent call last):
  File "client.py", line 21, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

C:\Users\Mohan Singh Kataria\Desktop\Chetali\JPMC-tech-task-1>python server.py
Traceback (most recent call last):
  File "server.py", line 21, in <module>
    from itertools import izip
ImportError: cannot import name 'izip' from 'itertools' (unknown location)

got the above errors while first time running the files in admin mode,Please help.
Thanks
using python version 3.7.4
using Windows 10 OS

**Comment by Ankush-Roy-007** [comment]
i am also facing 1st and 3rd problem, if you are the solution can you please share it with me

**Comment by YarilenkaBenitesMozo** [comment]
Hello, i was facaing that too, you need to add parenthesis after print.
