### ISSUE TITLE
KeyError: 'ABC'

### ISSUE THREAD

**Issue by mon2barot** [insidesherpa/bank-mergeCoTechTask1#54]
# Main
if __name__ == "__main__":
  for _ in range(N):
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
    prices = {}
    for quote in quotes:
      stock, bid_price, ask_price, price = getDataPoint(quote)
      print ("Quoted %s at (bid:%s, ask:%s, price:%s)" % (stock, bid_price, ask_price, price))
  
  print ("Ratio %s" % getRatio(prices['ABC'], prices['DEF']))
_______________________________________________________________________________________________

I'm not sure what the problem is but I run into the KeyError: 'ABC'

![JPMCT1](https://user-images.githubusercontent.com/62860732/79920807-d2773a80-83e5-11ea-92fe-bee8408ad651.PNG)

**Comment by kartikraj** [comment]
even i am getting the same error.
did u find any solution

**Comment by mon2barot** [comment]
Yes! I used the following code. 
if __name__ == "__main__":
  for _ in range(N):
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
    prices = {}
    for quote in quotes:
      stock, bid_price, ask_price, price = getDataPoint(quote)
      **_prices[stock] = price_** <- make sure to include this line. 
      print ("Quoted %s at (bid:%s, ask:%s, price:%s)" % (stock, bid_price, ask_price, price))
  print ("Ratio %s" % (getRatio(prices['ABC'], prices['DEF'])))

**Comment by kartikraj** [comment]
than you!!
