### ISSUE TITLE
Troubles Creating Patch File (Task 1)

### ISSUE THREAD

**Issue by cathy-yue** [insidesherpa/bank-mergeCoTechTask1#55]
Hello!

I finished the first task and the bonus as well. However, I followed the instructions on creating the patch file but it simply did not work. I did not get any error messages or anything. I ran the command, press enter, and nothing happened. I am working on a Windows operating system and I'm using Google Chrome. I am aware that after I ran "git commit -m 'Create Patch File'" it prints "Oh branch master nothing to commit, working tree clean". This was my third time trying to create the Patch File. The first time I had something that said "1 file changed, 1 insertion(+), 1 deletion(-)" like the instructions. I am not sure if this helps but I provided all the information I can!

Thank you

![PatchIssue](https://user-images.githubusercontent.com/64174326/80044643-26ac1880-84d3-11ea-8f2d-cc2170feccb2.png)

**Comment by advaith-unnikrishnan** [comment]
Hi @cathy-yue  I had similar issue when I ran `ls` command it listed the patch file along with the other files. But it was not listed in left side panel. **When I downloaded the zip file the patch file was there**. I think this will help you with the issue.

**Comment by cathy-yue** [comment]
> Hi @cathy-yue I had similar issue when I ran `ls` command it listed the patch file along with the other files. But it was not listed in left side panel. **When I downloaded the zip file the patch file was there**. I think this will help you with the issue.

Hello! That is very strange that it was't listed on the left side panel but what you said helped me out. Thank you!
