### ISSUE TITLE
Indentation error in task 1 (in  #Main)

### ISSUE THREAD

**Issue by Sreejan-22** [insidesherpa/bank-mergeCoTechTask1#57]
![Img1](https://user-images.githubusercontent.com/64251207/80190230-9506ed00-8631-11ea-9edb-d7bc852734bf.png)

The above link contains the screenshot.
OS is Windows 10, Browser is Google Chrome. The task is being done online on Repl.it
I am unable to proceed due to the indentation error

**Comment by akashmdubey** [comment]
i am stuck on the same issue. did you proceed?

**Comment by Sreejan-22** [comment]
> i am stuck on the same issue. did you proceed?

Not Yet bro

**Comment by rajesh9080813773** [comment]
Iam stuck on the same issues if you have proceeded further please explain how to resolve this error

**Comment by aholley30** [comment]
I was able to fix this error by redoing all of the indentation in that loop

**Comment by Sreejan-22** [comment]
> Iam stuck on the same issues if you have proceeded further please explain how to resolve this error

Actually the website got hanged in the process. So I had to redo everything and it got indented properly in this attempt.
