### ISSUE TITLE
I am unable to generate the patch file. I have tried running again everything thrice. 

### ISSUE THREAD

**Issue by jshubhi** [insidesherpa/bank-mergeCoTechTask1#59]
![Screenshot (83)](https://user-images.githubusercontent.com/63740932/80244916-69165680-8687-11ea-9bd0-8f837b922d1e.png)

![Screenshot (85)](https://user-images.githubusercontent.com/63740932/80244970-7fbcad80-8687-11ea-9565-5d41105f00fa.png)

**Comment by rohitm131** [comment]
read issue #40

**Comment by samar08** [comment]
I got the same issue. Have you resoled it?

**Comment by rohitm131** [comment]
yes my issue is resolved. Either u can copy the file to another file as mentioned in ussue #40 or can refresh the page once when finished running the command..
In my case it is making file at different place so i didn't executed the mv <"File Name "> command.

**Comment by tripathi-abhishek** [comment]
![efwefwef](https://user-images.githubusercontent.com/43468297/80681638-b444c500-8ade-11ea-8fc8-9f181d1430b3.jpg)

cant go any further. what to do??

**Comment by melvinmsm** [comment]
> ![efwefwef](https://user-images.githubusercontent.com/43468297/80681638-b444c500-8ade-11ea-8fc8-9f181d1430b3.jpg)
> 
> cant go any further. what to do??

You just have to initialize a git repository using 'git init' command and then follow the rest of the steps.
