### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by prakashpkb** [insidesherpa/bank-mergeCoTechTask1#61]
C:\WINDOWS\system32>cd \Users\91700\JPMC-tech-task-1

C:\Users\91700\JPMC-tech-task-1>python server.py
  File "server.py", line 217
    print 'HTTP server started on port 8080'
                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('HTTP server started on port 8080')?

**Comment by buildhigh20** [comment]
> C:\WINDOWS\system32>cd \Users\91700\JPMC-tech-task-1
> 
> C:\Users\91700\JPMC-tech-task-1>python server.py
> File "server.py", line 217
> print 'HTTP server started on port 8080'
> ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print('HTTP server started on port 8080')?

I am also getting the same issue.  Is it now running properly?

**Comment by naveed3923** [comment]
The parentheses for print command in server file are missing. 
for example: print 'HTTP server started on port 8080' (wrong way of using a print statement)
 The correct way would be: print('HTTP server started on port 8080')
As you may see the parentheses are needed while executing a print statement.

**Comment by buildhigh20** [comment]
> The parentheses for print command in server file are missing.
> for example: print 'HTTP server started on port 8080' (wrong way of using a print statement)
> The correct way would be: print('HTTP server started on port 8080')
> As you may see the parentheses are needed while executing a print statement.

I have put parentheses also,but now it is showing "Unable to initialize device PRN"

**Comment by AlankrithaShekar** [comment]
It's mostly because your version of python is 3, so clone JPMC-tech-task-1-py3 instead, it might work

**Comment by 30Ankita** [comment]
> It's mostly because your version of python is 3, so clone JPMC-tech-task-1-py3 instead, it might work

no such file or repositry found error

**Comment by samriddhi2400** [comment]
> C:\WINDOWS\system32>cd \Users\91700\JPMC-tech-task-1
> 
> C:\Users\91700\JPMC-tech-task-1>python server.py
> File "server.py", line 217
> print 'HTTP server started on port 8080'
> ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print('HTTP server started on port 8080')?

**Comment by samriddhi2400** [comment]
Did you find a solution to it?
