### ISSUE TITLE
Patch file not showing in the downloaded zip file

### ISSUE THREAD

**Issue by jshubhi** [insidesherpa/bank-mergeCoTechTask1#62]
![Screenshot (88)](https://user-images.githubusercontent.com/63740932/80287148-6bdb7f00-874d-11ea-8fad-113a129e4ccd.png)
![Screenshot (89)](https://user-images.githubusercontent.com/63740932/80287149-6da54280-874d-11ea-9698-92eaba7097ec.png)
![Screenshot (90)](https://user-images.githubusercontent.com/63740932/80287150-6e3dd900-874d-11ea-92c7-8b5401b4af86.png)

**Comment by kartikraj** [comment]
same problem

**Comment by jshubhi** [comment]
@jbf-insidesherpa please resolve this

**Comment by kartikraj** [comment]
I just copied the contents of patch file and pasted in notepad ,then renamed it with (.patch) extension , successfully submitted.
