### ISSUE TITLE
Server.py Issue

### ISSUE THREAD

**Issue by buildhigh20** [insidesherpa/bank-mergeCoTechTask1#65]
![Screenshot (32)](https://user-images.githubusercontent.com/52049742/80317949-643ad980-8824-11ea-9ece-3178c2f699bd.png)

Unable to connect with server.py and client.py

**Comment by AlankrithaShekar** [comment]
I got the same issue, I put the statement in print()

**Comment by buildhigh20** [comment]
> I got the same issue, I put the statement in print()

Thanks, but now problem is resolve
