### ISSUE TITLE
Not able to create the patch file

### ISSUE THREAD

**Issue by harshul21** [insidesherpa/bank-mergeCoTechTask1#72]
followed all the instructions in proper order but not able to create patch file

**Comment by shaonakundu** [comment]
not able to create the patch file even after doing all the steps. the file doesnot appear in the left panel

**Comment by isakshamgupta** [comment]
same problem not able to create patch file

**Comment by saidrishya** [comment]
Same problem

**Comment by PranavKapoor28** [comment]
Same Problem

**Comment by Pranathi-star** [comment]
fatal: not a git repository (or any parent up to mount point /home/runner)
I am getting this error when I run the command git add -A in REPL

**Comment by searchformyusername** [comment]
Are you all getting error when working in REPL?
for local people u can clone repo from here only, this will solve the issue.

**Comment by nehasangeetajha** [comment]
yes the same problem
Instead of patch file, a git folder is created

**Comment by searchformyusername** [comment]
@nehasangeetajha try by cloning [this](https://github.com/insidesherpa/JPMC-tech-task-1-PY3.git) repo

**Comment by ayushnanda21** [comment]
how to clone this repo

**Comment by searchformyusername** [comment]
@ayushnanda21 use this command
`git clone https://github.com/insidesherpa/JPMC-tech-task-1-PY3.git`

**Comment by Pranathi-star** [comment]
> fatal: not a git repository (or any parent up to mount point /home/runner)
> I am getting this error when I run the command git add -A in REPL

If anyone is getting the same error try git init on a fresh command line and then try the add command. It worked for me :)

**Comment by harshul21** [comment]
Those who are not able to see the patch file in their left column after doing the necessary step. Download the zip file you will be able to see your patch file there.

**Comment by ayushnanda21** [comment]
Yess,unzip the file and you will be able to find the patch file

**Comment by Aniruddhmuley2001** [comment]
@harshul21 Agreed on this, it works well.

**Comment by shaonakundu** [comment]
Si we have to download the git zip file? Because a git folder is created

**Comment by shaonakundu** [comment]
Means the git folder to unzip?

**Comment by manavsharma136** [comment]
> yes the same problem
> Instead of patch file, a git folder is created

yes same problem how to solve ?

**Comment by searchformyusername** [comment]
@manavsharma136 
unzip the file and you will be able to find the patch file
