### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by mjmaurya** [insidesherpa/bank-mergeCoTechTask1#77]
prices = {}
              ^
IndentationError: unindent does not match any outer 
indentation level

**Comment by nikita9604** [comment]
Follow WORKAROUND OPTION 2, you will be able to do it.
When you make changes, remove all previous comments and hit enter, then add your changes step by step following the right indentation. It should work properly. Here's a link to a gif/screencast that shows the workaround: http://tiny.cc/u6j2ez

**Comment by SurajPatidar201198** [comment]
I have done all that but still it is showing the same error @nikita9604

**Comment by apurvahegde2000** [comment]
I have the same issue. I followed Workaround option2 but still, the problem persists

**Comment by apurvahegde2000** [comment]
I solved the issue by manually typing the whole code in workbench1 and then renaming and then moving the file and deleting the previous file.

**Comment by SurajPatidar201198** [comment]
I have first copied whole code to VS code then I have corrected  my indentation then again pasted it there and issue is solved.

**Comment by nehal-backspace** [comment]
copied whole code and paste it to formatter here : https://www.tutorialspoint.com/online_python_formatter.htm

and then just pasted it

**Comment by tharun143** [comment]
Try adding indentations from under the line #main. It worked for me

**Comment by mjmaurya** [comment]
I solved the issue.
