### ISSUE TITLE
Unable to create a patch file

### ISSUE THREAD

**Issue by Aniruddhmuley2001** [insidesherpa/bank-mergeCoTechTask1#79]
I was working on the REPL environment, and after following the steps of creating a patch file, I did not get the patch file created in the files option

**Comment by harshul21** [comment]
after doing all the necessary steps go for downloading the zip file there you will get your patch file.

**Comment by vkn84527** [comment]
> I was working on the REPL environment, and after following the steps of creating a patch file, I did not get the patch file created in the files option

the same problem with me also doing same step but it showing error???

**Comment by vkn84527** [comment]
![Annotation 2020-05-03 104014](https://user-images.githubusercontent.com/44707673/80899522-a4bbbb00-8d2e-11ea-9468-233f5df4dfce.png)

**Comment by vkn84527** [comment]
showing this what i have to do please reply me??

**Comment by Pawansinghla** [comment]
no need to execute cd commadn you already in module_1 directory

**Comment by Pawansinghla** [comment]
> I was working on the REPL environment, and after following the steps of creating a patch file, I did not get the patch file created in the files option

i m getting same error

**Comment by Pawansinghla** [comment]
> after doing all the necessary steps go for downloading the zip file there you will get your patch file.

ptach file is not generated, now what i do?

**Comment by Pawansinghla** [comment]
> showing this what i have to do please reply me??

no need to execute cd command, you are already in module_1 directory

**Comment by AmanGoyal31** [comment]
> I was working on the REPL environment, and after following the steps of creating a patch file, I did not get the patch file created in the files option

same issue

**Comment by purvansh11** [comment]
> I was working on the REPL environment, and after following the steps of creating a patch file, I did not get the patch file created in the files option

Same issue...
After running the main.py file by clicking on start, I am recieving the below attached error

![Screenshot (115)](https://user-images.githubusercontent.com/43903717/80970985-b50c8c80-8e39-11ea-9498-ad1935a8989a.png)

**Comment by Mayank-7** [comment]
![Screenshot (86)](https://user-images.githubusercontent.com/52287975/81004682-62979400-8e6a-11ea-82f5-b25eced4e83a.png)
followed all the steps but Patch file is not getting created. Even zip file doesn't contain the patch file. Please Help

**Comment by vkn84527** [comment]
hey mayank did u register first your name and mail on there through command ????if not then register then it will work.

**Comment by Mayank-7** [comment]
Yes, I did now, I got my patch file in the sidebar but when I download zip there is no patch file in it. What to do?

**Comment by vkn84527** [comment]
then again do all things from begin, see pdf carefully and do step by step.

**Comment by AmanGoyal31** [comment]
> showing this what i have to do please reply me??

skip jpm_module_1
and continue the rest of part

**Comment by AmanGoyal31** [comment]
> ![Screenshot (86)](https://user-images.githubusercontent.com/52287975/81004682-62979400-8e6a-11ea-82f5-b25eced4e83a.png)
> followed all the steps but Patch file is not getting created. Even zip file doesn't contain the patch file. Please Help

dont run last command line .
after (git format-patch -1 HEAD ) look in left side, you will get the patch file now download it 
and don't run mv 0001-create-patch-file.patch ../. command

**Comment by deepakkumarkgs** [comment]
Downloaded zip but my patch file seems to be missing. Any idea why?
